name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "**.kt"
      - "**.kts"
      - "**.toml"
      - "**.xml"
      - ".github/workflows/*.yml"
  pull_request:
    branches:
      - "*"
    paths:
      - "**.kt"
      - "**.kts"
      - "**.toml"
      - "**.xml"
      - ".github/workflows/*.yml"

permissions:
  contents: read

jobs:
  pre_ci:
    uses: SDLMoe/.github/.github/workflows/pre_ci.yml@master

  check:
    name: Format and Test
    needs: pre_ci
    if: needs.pre_ci.outputs.continue
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - run: ./gradlew spotlessCheck test --no-daemon
